pref("extensions.zotero-ai-reading.aiURL", "https://chatgpt.com");
pref("extensions.zotero-ai-reading.aiPreset", "chatgpt");
pref("extensions.zotero-ai-reading.aiPresetMigrated", false);
pref("extensions.zotero-ai-reading.transferMode", "file");
pref("extensions.zotero-ai-reading.openAIPage", true);
pref("extensions.zotero-ai-reading.openInReaderPane", false);
pref("extensions.zotero-ai-reading.readerPaneWidth", 520);
pref("extensions.zotero-ai-reading.readerConversationURLs", "{}");
pref("extensions.zotero-ai-reading.autoPaste", true);
pref("extensions.zotero-ai-reading.pasteDelayMs", 2500);
pref("extensions.zotero-ai-reading.maxTextChars", 120000);
pref("extensions.zotero-ai-reading.prompt", "请以我刚上传的 PDF 文件作为主要来源。");
pref("extensions.zotero-ai-reading.extraPrompt", "");
